export const dummyjsonURL = `https://dummyjson.com`;
export const pageLimit = 30;
export const routes = {
	home: { path: "/" },
	products: { path: "/products" },
	product: { path: "/product" },
	news: { path: "/news" },
	cart: { path: "/cart"},
	order: {path: "/order"},
	post: { path: "/post" },
	user: { path: "/user"},
	login: {path: "/login"},
	register: {path: "/register"},
	notFound: { path: "/page_not_found" },
};
export const encryptKey = 'StoreeEncryptKey2023';
export const states = [
	'Alabama (AL)',
	'Alaska (AK)',
	'Arizona (AZ)',
	'Arkansas (AR)',
	'California (CA)',
	'Colorado (CO)',
	'Connecticut (CT)',
	'Delaware (DE)',
	'Florida (FL)',
	'Georgia (GA)',
	'Hawaii (HI)',
	'Idaho (ID)',
	'Illinois (IL)',
	'Indiana (IN)',
	'Iowa (IA)',
	'Kansas (KS)',
	'Kentucky (KY)',
	'Louisiana (LA)',
	'Maine (ME)',
	'Maryland (MD)',
	'Massachusetts (MA)',
	'Michigan (MI)',
	'Minnesota (MN)',
	'Mississippi (MS)',
	'Missouri (MO)',
	'Montana (MT)',
	'Nebraska (NE)',
	'Nevada (NV)',
	'New Hampshire (NH)',
	'New Jersey (NJ)',
	'New Mexico (NM)',
	'New York (NY)',
	'North Carolina (NC)',
	'North Dakota (ND)',
	'Ohio (OH)',
	'Oklahoma (OK)',
	'Oregon (OR)',
	'Pennsylvania (PA)',
	'Rhode Island (RI)',
	'South Carolina (SC)',
	'South Dakota (SD)',
	'Tennessee (TN)',
	'Texas (TX)',
	'Utah (UT)',
	'Vermont (VT)',
	'Virginia (VA)',
	'Washington (WA)',
	'West Virginia (WV)',
	'Wisconsin (WI)',
	'Wyoming (WY)',
]
export const shipmentMethods = {
	'warehouse': {
		value: 'warehouse',
		label: 'Pick up from warehouse',
	},
	'courier': {
		value: 'courier',
		label: 'Courier delivery',
	},
	'postOffice': {
		value: 'postOffice',
		label: 'Delivery to the post office',
	},
	'airDrone': {
		value: 'airDrone',
		label: 'Air drone shipment',
	},
}